package com.laboratory.system.role.model;

import java.util.Date;

public class RoleResource {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role_resource.id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role_resource.role_id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role_resource.resource_id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    private Integer resourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role_resource.create_time
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role_resource.id
     *
     * @return the value of lab_role_resource.id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role_resource.id
     *
     * @param id the value for lab_role_resource.id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role_resource.role_id
     *
     * @return the value of lab_role_resource.role_id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role_resource.role_id
     *
     * @param roleId the value for lab_role_resource.role_id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role_resource.resource_id
     *
     * @return the value of lab_role_resource.resource_id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public Integer getResourceId() {
        return resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role_resource.resource_id
     *
     * @param resourceId the value for lab_role_resource.resource_id
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role_resource.create_time
     *
     * @return the value of lab_role_resource.create_time
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role_resource.create_time
     *
     * @param createTime the value for lab_role_resource.create_time
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}