package com.laboratory.system.role.model;

import java.util.Date;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role.id
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role.role_name
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role.is_used
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    private String isUsed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role.create_time
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role.update_time
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_role.comment
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role.id
     *
     * @return the value of lab_role.id
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role.id
     *
     * @param id the value for lab_role.id
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role.role_name
     *
     * @return the value of lab_role.role_name
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role.role_name
     *
     * @param roleName the value for lab_role.role_name
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role.is_used
     *
     * @return the value of lab_role.is_used
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public String getIsUsed() {
        return isUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role.is_used
     *
     * @param isUsed the value for lab_role.is_used
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public void setIsUsed(String isUsed) {
        this.isUsed = isUsed == null ? null : isUsed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role.create_time
     *
     * @return the value of lab_role.create_time
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role.create_time
     *
     * @param createTime the value for lab_role.create_time
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role.update_time
     *
     * @return the value of lab_role.update_time
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role.update_time
     *
     * @param updateTime the value for lab_role.update_time
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_role.comment
     *
     * @return the value of lab_role.comment
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_role.comment
     *
     * @param comment the value for lab_role.comment
     *
     * @mbg.generated Tue Dec 12 16:55:30 CST 2017
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}