package com.laboratory.system.role.model;

import java.util.Date;

public class UserRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_user_role.id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_user_role.user_id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_user_role.role_id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lab_user_role.create_time
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_user_role.id
     *
     * @return the value of lab_user_role.id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_user_role.id
     *
     * @param id the value for lab_user_role.id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_user_role.user_id
     *
     * @return the value of lab_user_role.user_id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_user_role.user_id
     *
     * @param userId the value for lab_user_role.user_id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_user_role.role_id
     *
     * @return the value of lab_user_role.role_id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_user_role.role_id
     *
     * @param roleId the value for lab_user_role.role_id
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lab_user_role.create_time
     *
     * @return the value of lab_user_role.create_time
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lab_user_role.create_time
     *
     * @param createTime the value for lab_user_role.create_time
     *
     * @mbg.generated Thu Dec 21 13:29:55 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}