package com.laboratory.system.role.dao;

import com.laboratory.system.role.model.RoleResource;

import java.util.List;

public interface RoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_role_resource
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_role_resource
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    int insert(RoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_role_resource
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    RoleResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_role_resource
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    List<RoleResource> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_role_resource
     *
     * @mbg.generated Tue Dec 12 16:55:56 CST 2017
     */
    int updateByPrimaryKey(RoleResource record);
}