package com.laboratory.system.resource.dao;
;

import com.laboratory.system.resource.model.Resources;

import java.util.List;

public interface ResourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_resources
     *
     * @mbg.generated Tue Dec 12 16:53:29 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_resources
     *
     * @mbg.generated Tue Dec 12 16:53:29 CST 2017
     */
    int insert(Resources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_resources
     *
     * @mbg.generated Tue Dec 12 16:53:29 CST 2017
     */
    Resources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_resources
     *
     * @mbg.generated Tue Dec 12 16:53:29 CST 2017
     */
    List<Resources> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lab_resources
     *
     * @mbg.generated Tue Dec 12 16:53:29 CST 2017
     */
    int updateByPrimaryKey(Resources record);
}